---
- name: Configure web server and deploy page
  hosts: web

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Deploy the web page
      copy:
        src: files/index.html
        dest: /var/www/html/index.html

    - name: Ensure NGINX is running
      service:
        name: nginx
        state: started
        enabled: true
